import { FlatCompat } from '@eslint/eslintrc';

const compat = new FlatCompat({ baseDirectory: import.meta.dirname });

/**
 * ESLint, restored.
 *
 * The `lint` script was deleted from both package.json files earlier in this
 * project's history and no config or dependency was left behind, so for a long
 * stretch `tsc` was the only static analysis running. That is exactly where the
 * two worst bugs of the last review came from, and both are rules that ship in
 * this config for free:
 *
 *  - `react-hooks/exhaustive-deps` — useJournalMemory called
 *    memoryKey.confirmKeyProven() from useCallbacks that omitted `memoryKey`,
 *    so both permanently ran the first render's closure and the promotion
 *    never happened. A 33-agent hunt found it. This rule finds it instantly.
 *  - `react-hooks/rules-of-hooks` — StorageReceiptViewer called useModalFocus
 *    after `if (!receipt) return null`, which React throws on.
 *
 * Hand-written static guards in lib/hooks/wiring.test.ts were standing in for
 * this. They stay — they encode repo-specific invariants a linter cannot know —
 * but they should not have been carrying the general case alone.
 */
const config = [
  {
    ignores: [
      '.next/**',
      'public/**',
      'node_modules/**',
      // Emitted by the 0G toolchain and by Playwright captures; not ours.
      '**/typechain-types/**',
      // Generated by Next on every build, with triple-slash references the
      // TypeScript rule objects to. Linting it means editing a file Next
      // rewrites.
      'next-env.d.ts',
    ],
  },
  ...compat.extends('next/core-web-vitals', 'next/typescript'),
  {
    // Config files conventionally export an object literal directly, and dev
    // probe scripts under scripts/ are diagnostics, not shipped code.
    files: ['**/*.config.mjs', '**/scripts/**'],
    rules: {
      'import/no-anonymous-default-export': 'off',
      '@typescript-eslint/no-unused-expressions': 'off',
    },
  },
  {
    rules: {
      // The two that would have caught this session's worst bugs. Errors, not
      // warnings: a warning in a repo with no lint step in CI is a comment.
      'react-hooks/rules-of-hooks': 'error',
      'react-hooks/exhaustive-deps': 'error',
      // The codebase deliberately uses `any` in a few adapter seams around
      // untyped SDK surfaces; those carry explicit disable comments.
      '@typescript-eslint/no-explicit-any': 'warn',
      '@typescript-eslint/no-unused-vars': [
        'error',
        { argsIgnorePattern: '^_', varsIgnorePattern: '^_' },
      ],
    },
  },
];

export default config;
